### ISSUE TITLE
[collector metrics exporter] collisions with extra labels and metric labels

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#352]
Currently, with `service_resource_labels` enabled (which is enabled by default), it is possible to get duplicate labels on metrics if the service_name label is also set on the metric itself.  The same applies to any other labels added by the exporter.

As an example:
```yaml
level: error
ts: 1649711917.6179736
caller: 'collector/metrics.go:292'
msg: Unable to send metric descriptor.
error: >-
  rpc error: code = InvalidArgument desc = Field metricDescriptor.labels[3].key
  had an invalid value of "service_name": Duplicate label key encountered.
metric_descriptor: >-
  name:"ex_com_one" type:"workload.googleapis.com/ex_com_one"
  labels:{key:"service_name"} labels:{key:"service_instance_id"}
  labels:{key:"ex_com_lemons"} labels:{key:"service_name"}
  labels:{key:"telemetry_sdk_language"} labels:{key:"telemetry_sdk_name"}
  labels:{key:"telemetry_sdk_version"} labels:{key:"A"} labels:{key:"B"}
  labels:{key:"C"} metric_kind:GAUGE value_type:DOUBLE display_name:"ex_com_one"
stacktrace: "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportMetricDescriptor\n\t/workspace/exporter/collector/metrics.go:292\ngithub.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportMetricDescriptorRunner\n\t/workspace/exporter/collector/metrics.go:262"
---
level: error
ts: 1649711917.6435902
caller: 'collector/metrics.go:292'
msg: Unable to send metric descriptor.
error: >-
  rpc error: code = InvalidArgument desc = Field metricDescriptor.labels[3].key
  had an invalid value of "service_name": Duplicate label key encountered.
metric_descriptor: >-
  name:"ex_com_two" type:"workload.googleapis.com/ex_com_two"
  labels:{key:"service_name"} labels:{key:"service_instance_id"}
  labels:{key:"ex_com_lemons"} labels:{key:"service_name"}
  labels:{key:"telemetry_sdk_language"} labels:{key:"telemetry_sdk_name"}
  labels:{key:"telemetry_sdk_version"} labels:{key:"A"} labels:{key:"B"}
  labels:{key:"C"} metric_kind:CUMULATIVE value_type:DISTRIBUTION
  display_name:"ex_com_two"
stacktrace: "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportMetricDescriptor\n\t/workspace/exporter/collector/metrics.go:292\ngithub.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportMetricDescriptorRunner\n\t/workspace/exporter/collector/metrics.go:262"
```

We should come up with a method for preventing those collisions.  Note that the root cause is that the opentelemetry-go's prometheus exporter incorrectly translates resource information to metric labels: https://github.com/open-telemetry/opentelemetry-go/blob/8c0951ea94cb20bd9e2338b8fdc20036b8cf995b/exporters/prometheus/prometheus.go#L302
