### ISSUE TITLE
OTEL Exporter maps Prometheus metrics to generic_task monitored resource

### ISSUE THREAD

**Issue by jsirianni** [GoogleCloudPlatform/opentelemetry-operations-go#434]
### Problem

I am scraping Prometheus metrics (Aerospike exporter) using the Prometheus receiver. The google exporter is mapping these metrics to `generic_task` monitored resource type when I would expect it to map to `generic_node`.

This is because Prometheus exporter sets the following resource labels
- service.name (maps to generic_task's `job` field)
- service.instance.id (maps to generic_task's `taskID` field)

Resource labels (From logging exporter)
```
Resource labels:
     -> service.name: STRING(aerospike)
     -> service.instance.id: STRING(127.0.0.1:9145)
     -> net.host.port: STRING(9145)
     -> http.scheme: STRING(http)
     -> host.name: STRING(fedora)
     -> os.type: STRING(linux)
```

![Screenshot from 2022-06-20 17-36-17](https://user-images.githubusercontent.com/23043836/174680592-0a37b8b0-f34f-497a-abe9-733760799d06.png)

### Expected Behavior

I would expect to map Prometheus metrics to `generic_node`. The [description for Generic Task](https://cloud.google.com/monitoring/api/resources#tag_generic_task) does not match Prometheus metrics:
>```Description: A generic task identifies an application process for which no more specific resource is applicable, such as a process scheduled by a custom orchestration system. The label values must uniquely identify the task.```

The [description](https://cloud.google.com/monitoring/api/resources#tag_generic_node) for `generic_node` makes more sense in my opinion:
>```Description: A generic node identifies a machine or other computational resource for which no more specific resource type is applicable. The label values must uniquely identify the node.```

I have considered renaming service.name and service.instance.id, however, Open Telemetry [Semantic Conventions](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/#service) encourage their use. 

### Environment

Collector: opentelemetry-collector-contrib.jsirianni main branch and v0.53.0

Configuration:
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'aerospike'
        scrape_interval: 30s
        static_configs:
        - targets:
          - '127.0.0.1:9145'

processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters: 
  googlecloud:
    metric:
      prefix: workload.googleapis.com/aerospike
      resource_filters:
        - prefix: service.*

  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      processors:
      - resourcedetection/system
      - batch
      exporters:
      - googlecloud
      - logging
```

[Mapping code](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/internal/resourcemapping/resourcemapping.go#L102)
```go
		genericTask: {
			location: {
				otelKeys: []string{
					string(semconv.CloudAvailabilityZoneKey),
					string(semconv.CloudRegionKey),
				},
				fallbackLiteral: "global",
			},
			namespace: {otelKeys: []string{string(semconv.ServiceNamespaceKey)}},
			job:       {otelKeys: []string{string(semconv.ServiceNameKey)}},
			taskID:    {otelKeys: []string{string(semconv.ServiceInstanceIDKey)}},
		},
		genericNode: {
			location: {
				otelKeys: []string{
					string(semconv.CloudAvailabilityZoneKey),
					string(semconv.CloudRegionKey),
				},
				fallbackLiteral: "global",
			},
			namespace: {otelKeys: []string{string(semconv.ServiceNamespaceKey)}},
			nodeID:    {otelKeys: []string{string(semconv.HostIDKey), string(semconv.HostNameKey)}},
		},
```
