### ISSUE TITLE
Facing "panic: assignment to entry in nil map" when trying to export otlp logs to google cloud

### ISSUE THREAD

**Issue by kushal-ti** [GoogleCloudPlatform/opentelemetry-operations-go#435]
i have the following configuration for my otel collector 
```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  googlecloud:
    retry_on_failure:
      enabled: false
    project: project-name
    log:
      default_log_name: opentelemetry.io/collector-exported-log


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, googlecloud]

  extensions: [health_check, pprof, zpages]

```
When I run the collector with just the loggin exporter in my logs pipeline, things work fine and i can see the logs in the otel stdout, but when i run it with googlecloud exporter, i get the following error 

```go
panic: assignment to entry in nil map

goroutine 145 [running]:
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.logMapper.logToSplitEntries({{0xc000682420}, {{{0xc00029a2a0, 0x27}, {0x0, {...}, 0x0}}, {0xc0009c9818, 0x11}, {0x4c4bb10, 0x2b}, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector@v0.30.2-0.20220512190557-875976f87023/logs.go:288 +0xd7
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.logMapper.createEntries({{0xc000682420}, {{{0xc00029a2a0, 0x27}, {0x0, {...}, 0x0}}, {0xc0009c9818, 0x11}, {0x4c4bb10, 0x2b}, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector@v0.30.2-0.20220512190557-875976f87023/logs.go:201 +0x431
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*LogsExporter).PushLogs(0xc000878900, {0x5492a30, 0xc000c42210}, {0x0?})
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector@v0.30.2-0.20220512190557-875976f87023/logs.go:133 +0xbb
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).export(0x7fe726bbb8e0?, {0x5492a30?, 0xc000c42210?})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/logs.go:65 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000c84a50, {0x54a5d40, 0xc000c421b0})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/common.go:225 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc0003f3200, {0x54a5d40?, 0xc000c421b0?})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/queued_retry.go:147 +0x156
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc000910498, {0x54a5d40, 0xc000c421b0})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/logs.go:131 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x472ba20?, 0xc000c421b0})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/queued_retry_inmemory.go:119 +0x5c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume(0x0?, {0x472ba20?, 0xc000c421b0?})
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82 +0x2c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2()
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69 +0xcd
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
	go.opentelemetry.io/collector@v0.53.0/exporter/exporterhelper/internal/bounded_memory_queue.go:63 +0x98
```

I'm facing this same error in local as well as production environments.

as far as i can tell this error only occurs when using the google cloud exporter for exporting logs. Exporting traces seems to be working fine.

**Comment by dashpole** [comment]
What version of the collector are you using?

cc @damemi

**Comment by damemi** [comment]
> What version of the collector are you using?

stack trace looks like its `0.53.0`, which I think is [pinned](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.53.0/exporter/googlecloudexporter/go.mod#L7) to v0.31.0 (`v0.30.2-0.20220512190557-875976f87023`)? That would point to this line that gets the log attribute: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.30.1/exporter/collector/logs.go#L228

Maybe we should check for `log.Attributes()` to be nil before calling `Get()` on it

**Comment by damemi** [comment]
Sorry I misread the log line, it's probably actually referring to [this line](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.31.0/exporter/collector/logs.go#L288) where we assign a label in a map. Working on a test and fix

**Comment by damemi** [comment]
@kushal-ti have you tried the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor)?

**Comment by kushal-ti** [comment]
@damemi i'm really sorry to keep bothering you regarding this, but based on this

> Maybe we should check for `log.Attributes()` to be nil before calling `Get()` on it

I assumed that if i added an attribute to my logs manually, using the attribute processor, before passing it to the googlecloud exporter it would have worked, but it still fails with the same error

This is my modified config 
```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
      
  # Collect own metrics
processors:
  batch:
  attributes:
    # Override the default log name.  `gcp.log_name` takes precedence
    # over the `default_log_name` specified in the exporter.
    actions:
      - key: gcp.log_name
        action: insert
        value: otel-collector-pipeline

exporters:
  logging:
    loglevel: debug
  googlecloud:
    retry_on_failure:
      enabled: true
    project: codenation-186008
    log:
      default_log_name: app


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [logging]

    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [file]

    logs:
      receivers: [otlp]
      processors: [batch, transform, attributes]
      exporters: [logging, googlecloud]

  extensions: [health_check, pprof, zpages]

```

And I can confirm that the attributes are being added to my logs, but it still doesn't seem to work. For the moment i'm hacking my way around it by sending logs to fluent bit which then sends it to otel collector (these logs have attributes added to them automaitcally by the fluent bit receiver) and these can then successfully be exported to gcp, however, going forwards it will be difficult for me to use this hack everywhere and i would really appreciate if there was any way to export logs directly from my application to otel and then to GCP

I understand that there was some kind of bug in the current release, but is there anyway i can modify the structure of my logs to sidestep that bug ?
