### ISSUE TITLE
Exporter does not recognize log levels or any extra attributes 

### ISSUE THREAD

**Issue by kushal-ti** [GoogleCloudPlatform/opentelemetry-operations-go#442]
I'm using the open telemetry filelog receiver to collect logs (since using the otlp log receiver is failing in the current release due to the issue mentioned here https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/435.) 
The output of the filelog receiver logs, after being passed through the processor in the otel collector, looks like this
```JSON
{
    "resourceLogs": [
        {
            "resource": {},
            "scopeLogs": [
                {
                    "scope": {},
                    "logRecords": [
                        {
                            "observedTimeUnixNano": "1655957310265130687",
                            "severityText": "INFO",
                            "body": {
                                "stringValue": "Entering healthCheckPost with list of 2 arguments"
                            },
                            "attributes": [
                                {
                                    "key": "gcp.log_name",
                                    "value": {
                                        "stringValue": "otel-collector-pipeline"
                                    }
                                },
                                {
                                    "key": "gcp.arguments",
                                    "value": {
                                        "stringValue": "[{\"type\": \"String\", \"value\": \"kushal\"}, {\"type\": \"CustomBody\", \"value\": {\"member1\":10,\"member2\":100,\"member3\":[10,100]}}]"
                                    }
                                } ... (truncated for brevity)
                            ],
                            "traceId": "e8f84199ef8f4e1779cd21577aaacbc1",
                            "spanId": "ee43d418bc51ca1f"
                        }
                    ]
                }
            ]
        }
    ]
}
``` 
However, this same log on the console looks like so 
![Screenshot from 2022-06-23 09-56-11](https://user-images.githubusercontent.com/88190553/175208976-ac6b1741-2d49-49e8-ab56-f4f5ad39afca.png)

According to the mapping in the logs data model mentioned here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#google-cloud-logging any extra attributes should be mentioned as gcp.* , but gcp.arguments attributes in the above log were dropped. https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/424 talks about non gcp.* attributes so i was under the implication that gcp.* attributes should have been retained, in the current release itself.

Additionally, it also does not retain the log severity, (INFO in this case), instead, the log severity I see on gcp console is default
Do i set some other property so that log severity is picked up by stackdriver?. Also, do gcp.* attributes only cover specific list of attributes that stackdriver recognises ? and if so, is there any documentation of this list?

For reference, this is my otel config file 
```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  filelog:
    include: [input_logs.json]
    start_at: end
    operators:
      - type: json_parser
        parse_from: body
        
  fluentforward:
    endpoint: 0.0.0.0:8000
  otlp:
    protocols:
      grpc:
      http:    
processors:
  batch:
  transform:
    logs:
      queries:
        - set(trace_id, attributes["trace_id"])
        - set(span_id, attributes["span_id"])
        - set(severity_text, attributes["severity"])
        - set(body, attributes["message"])

  attributes:
    # Override the default log name.  `gcp.log_name` takes precedence
    # over the `default_log_name` specified in the exporter.
    actions:
      - key: gcp.log_name
        action: insert
        value: otel-collector-pipeline
      - key: gcp.arguments
        from_attribute: arguments
        action: upsert

exporters:
  logging:
    loglevel: debug
  file:
    path: output_logs.json
  googlecloud:
    retry_on_failure:
      enabled: true
    project: codenation-186008
    log:
      default_log_name: app


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud]

    logs:
      receivers: [filelog]
      processors: [batch, transform, attributes]
      exporters: [file, googlecloud]

  extensions: [health_check, pprof, zpages]

```

**Comment by damemi** [comment]
Thanks for reporting this @kushal-ti. We did test the exporter using the filelog receiver's [severity parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/severity_parser.md) (before the transform processor was available, which I see you are using). Maybe because of that, we worked with some assumptions about the severity that were specific to the parser. I'll look into those and make sure we can parse `severityText` properly.

In the mean time, would you be able to try using the severity parsing operator to see if that works?

For the attributes, the intent of that wildcard `gcp.*` for "any additional fields" was to refer to any [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) or GCP-specific fields not explicitly called out in the doc. The exporter actually skips over attributes with `gcp.` when parsing them to labels, because we assume those have been parsed to LogEntry fields elsewhere in the exporter code. We should make this clearer in the docs, and may want to revisit that behavior if it's too aggressive.

The tl;dr is if you have your own attributes, you can just use your own naming style. All OTel attributes that can't be mapped to a GCP field get converted to labels on the entry.

**Comment by kushal-ti** [comment]
@damemi just an update, apparently just adding severity text isn't enough, you also need to add a severity number, 
After i modified my otel config file to look like this, i could see the logs turning up in gcp console with the proper severity level 

```YAML
transform:
    logs:
      queries:
        - set(trace_id, attributes["trace_id"])
        - set(span_id, attributes["span_id"])
        - set(severity_text, attributes["severity"])
        - set(severity_number, 9) where attributes["severity"] == "INFO"
        - set(severity_number, 13) where atributes["severity"] == "WARN"
        - set(severity_number, 17) where attributes["severity"] == "ERROR"
        - set(body, attributes["message"])
```
