### ISSUE TITLE
Collector Exporter: Support regex matching for metric resource_filters

### ISSUE THREAD

**Issue by jsirianni** [GoogleCloudPlatform/opentelemetry-operations-go#447]
It would be nice if metric.resource_filters supported regex matching in addition to string prefix. 

If I want to always copy all resource attributes, I need to define resource_filters like this:
```yaml
...
          metric:
            resource_filters:
              - prefix: a
              - prefix: A
              - prefix: b
              - prefix: B
              ...
              - prefix: z
              - prefix: Z
...
```

It would be nice if I could accomplish the same thing using the filter `*` or have an option to skip matching entirely and just copy all resource attributes to metric labels.

This is a big friction point for customers because they need to define a resource prefix for every receiver in their pipeline. Failing to do so will result in duplicate metric / time series errors. For example, Rabbitmq has metrics on a per queue basis. If The system has multiple queues, the Google API will reject these metrics (because they appear are duplicates) if the user has not configured the correct resource filter prefix.  

This configuration will not work until the user has added the correct resource filter prefix:
```yaml
receivers:
  rabbitmq:
    endpoint: http://localhost:15672
    collection_interval: 60s
    # From environment. See README.md.
    username: $RABBITMQ_USERNAME
    password: $RABBITMQ_PASSWORD

exporters: 
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - rabbitmq
      exporters:
      - googlecloud
  ```

These resource attributes are critical but omitted by default.

**Comment by dashpole** [comment]
Just curious, does this work?
```yaml
          metric:
            resource_filters:
              - prefix: ""
```
