### ISSUE TITLE
Resource mappings questions on googlecloud.OTLPDirect

### ISSUE THREAD

**Issue by CatherineF-dev** [GoogleCloudPlatform/opentelemetry-operations-go#453]
Want to migrate into OTLPDirect.

It needs two location labels `CloudAvailabilityZoneKey` and `CloudRegionKey`.
```
		k8sContainer: {
			location: {otelKeys: []string{
				string(semconv.CloudAvailabilityZoneKey),
				string(semconv.CloudRegionKey),
			}},
			clusterName:   {otelKeys: []string{string(semconv.K8SClusterNameKey)}},
			namespaceName: {otelKeys: []string{string(semconv.K8SNamespaceNameKey)}},
			podName:       {otelKeys: []string{string(semconv.K8SPodNameKey)}},
			containerName: {otelKeys: []string{string(semconv.K8SContainerNameKey)}},
		},
```
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/internal/resourcemapping/resourcemapping.go#L63-L72

Before, it only has one location label `location`
```
        - label_mappings:
          - source_key: location
            target_key: location
          - source_key: cluster_name
            target_key: cluster_name
          - source_key: container_name
            target_key: container_name
          - source_key: namespace_name
            target_key: namespace_name
          - source_key: pod_name
            target_key: pod_name
          source_type: k8s_container
          target_type: k8s_container
```

Is it okay only assign `location` to `CloudAvailabilityZoneKey/cloud.availability_zone`? Or need to assign a value to `CloudRegionKey` too?
