### ISSUE TITLE
Unable to send metric descriptor - request was missing field metricDescriptor.valueType

### ISSUE THREAD

**Issue by tiffanny29631** [GoogleCloudPlatform/opentelemetry-operations-go#529]
The `googlecloud` exporter is continuously having trouble sending metric descriptor and complaining with lots of logs with following error:

```
error   collector@v0.32.2/metrics.go:316        Unable to send metric descriptor. {"kind": "exporter", "data_type": "metrics", "name": "googlecloud", "error": "rpc error: code = InvalidArgument desc = Request was missing field metricDescriptor.valueType: The descriptor does not have the value type set.", "metric_descriptor": "name:\"internal_errors_total\"  type:\"custom.googleapis.com/opencensus/config_sync/internal_errors_total\"  labels:{key:\"instrumentation_source\"}  labels:{key:\"instrumentation_version\"}  metric_kind:CUMULATIVE  unit:\"1\"  description:\"The total number of internal errors triggered by Config Sync\"  display_name:\"opencensus/config_sync/internal_errors_total\""}
```

I'm using [Open Telemetry Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.54.0/exporter/googlecloudexporter) 0.54.0, the exporter configuration is closer to default 
```
googlecloud:
    metric:
      prefix: "custom.googleapis.com/opencensus/config_sync/"
      skip_create_descriptor: false
    retry_on_failure:
      enabled: false
    sending_queue:
      enabled: false
```

The metrics are accepted by `opencensus` receiver. I also see [this TODO](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/metrics.go#L314) that proposing reduce the duplicate error message, is it something to be expected in the near future?

Thanks!
