### ISSUE TITLE
Custom resource labels a missing when createMonitoredResource

### ISSUE THREAD

**Issue by tiffanny29631** [GoogleCloudPlatform/opentelemetry-operations-go#534]
We are trying to add some custom resource labels to have them converted with `resource_filter` into metric labels later. An example custom resource label looks like `configsync.sync.name`. 

We've verified that with `resource_to_telemetry_conversion` config in Prometheus exporter these custom labels can be correctly converted so they do exist fine.

From the testing so far those labels seem to be missing when exporting to GCM and I only get the labels specified in the [resource mapping](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.34.0/internal/resourcemapping/resourcemapping.go#L48). IIUC [this conversion](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.34.0/internal/resourcemapping/resourcemapping.go#L180) only includes the specified labels? Are custom resource labels processed somewhere else or dropped?

Thanks!

**Comment by damemi** [comment]
Hi @tiffanny29631, the attributes from `resource_filter` are parsed into extra labels during [this call](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.34.0/exporter/collector/metrics.go#L178) to [resourceToMetricLabels](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.34.0/exporter/collector/monitoredresource.go#L58). 

So, any resource attributes that match the prefix you set in `resource_filter` should get converted. Can you share a sample of your collector config?

**Comment by tiffanny29631** [comment]
Below is our Otel Configuration for GCM and Prom

```
    receivers:
      opencensus:
    exporters:
      prometheus:
        endpoint: :8675
        namespace: config_sync
      googlecloud:
        metric:
          prefix: "custom.googleapis.com/opencensus/config_sync/"
          skip_create_descriptor: true
          resource_filters:
            prefix: "config"
          instrumentation_library_labels: false
        retry_on_failure:
          enabled: false
        sending_queue:
          enabled: false
    processors:
      batch:
      resourcedetection:
        detectors: [env, gcp]
      filter/cloudmonitoring:
        metrics:
          include:
            match_type: regexp
            metric_names:
              - reconciler_errors
              - pipeline_error_observed
              - declared_resources
              - apply_operations_total
              - resource_fights_total
              - internal_errors_total
              - kcc_resource_count
              - resource_count
              - ready_resource_count
              - cluster_scoped_resource_count
              - resource_ns_count
              - api_duration_seconds
    extensions:
      health_check:
    service:
      extensions: [health_check]
      pipelines:
        metrics/cloudmonitoring:
          receivers: [opencensus]
          processors: [attributes, resource, resourcedetection, batch, filter/cloudmonitoring]
          exporters: [googlecloud]
        metrics/prometheus:
          receivers: [opencensus]
          processors: [batch]
          exporters: [prometheus]
```
