### ISSUE TITLE
Where did jsonPayload go in Cloud Logger?

### ISSUE THREAD

**Issue by chrisle** [GoogleCloudPlatform/opentelemetry-operations-go#589]
Maybe a month or so ago, when using this exporter with the OTel collector, I was able to verify things were working end-to-end because I would see jsonPayload in the Google Logging Explorer. 

Currently, they're not appearing, making me think I my export configuration isn't working. 

I'm sure the log entries are getting in because I had setup a BQ sink and found the log entries there but not in Logging Explorer. 

```yaml
# test_config.yaml

receivers:
  filelog/test:
    include:
      - /sample_logs/test.json
    start_at: beginning
    operators:
      - id: parse_json_data
        type: json_parser
        parse_to: body
        timestamp:
          parse_from: body.Time
          layout: '%Y-%m-%d %H:%M:%S,%L'
          location: UTC
      - id: set_source
        type: add
        field: body.sourcedata
        value: ttv_content_collect
      - id: set_log_name
        type: add
        field: attributes["gcp.log_name"]
        value: dev_vod_ams_syslog
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
  resourcedetection:
    detectors:
      - gcp
    timeout: 10s
extensions: {}
exporters:
  file/debug:
    path: /com.docker.devenvironments.code/debug.log
  logging/*:
    verbosity: detailed
  googlecloud:
    project: acn-agbg-data-migration
    retry_on_failure:
      enabled: false
service:
  pipelines:
    logs:
      receivers:
        - filelog/test
      processors:
        - memory_limiter
        - resourcedetection
      exporters:
        - file/debug
        - logging/*
        - googlecloud
  extensions: []
```

Google credentials are fine. I've set the environment variable `CLOUDSDK_CONFIG` and it picks up my credentials from `gcloud auth application-default login` just fine.

Running `observeiq-otel-collector --config test_config.yaml`, everything seem to also work. It reads the sample log, parses it, and exports to stdout, a file on the local disk, and google cloud as expected.

When I go to Cloud Logging Explorer, I thought I was supposed to be able to see several log entries that were sent by the exporter by using this query: `jsonPayload=*`.

Am I missing something?
