### ISSUE TITLE
Metrics WAL Error In Logs is misleading

### ISSUE THREAD

**Issue by cpheps** [GoogleCloudPlatform/opentelemetry-operations-go#653]
There's an error log printed every time the WAL is read and it gives the impression in the collector logs that the WAL is not working. The log is printed on every collector interval and fills the collector logs with errors.

The following log is filling the collector logs when the metrics WAL is enabled.

```json
{
  "level": "error",
  "ts": "2023-06-28T08:18:28.549-0400",
  "caller": "collector@v0.39.2/metrics.go:605",
  "msg": "error reading WAL and exporting: out of range",
  "kind": "exporter",
  "data_type": "metrics",
  "name": "googlecloud/gcp",
  "stacktrace": "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).runWALReadAndExportLoop\n\t/Users/cphelps/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.39.2/metrics.go:605"
}
```

It seems this is expected and not uncommon from [this](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/metrics.go#L598-L603) comment. This is misleading to the collector user as metrics are still being successfully sent to GCP.

**Comment by cpheps** [comment]
Thanks for the clarification @damemi. I was restarting the collector and manually deleting the WAL between restarts. Assuming this would give me a clean environment and not hit this issue.

Let me know if you need any more information on what I'm seeing.

**Comment by cpheps** [comment]
@damemi I do not get any API errors if I leave the WAL alone between restarts. I seem to get the `out of range` error no matter what I try. It consistently prints on every collection interval.

Just for context here is the config I'm using

```yaml
receivers:
    hostmetrics:
        collection_interval: 60s
        scrapers:
            filesystem: null
            load: null
            memory: null
            network: null
            paging: null
processors:
    batch:
exporters:
    googlecloud:
        metric:
            experimental_wal_config:
                directory: ./storage
                max_backoff: 60m
        project: otel-dev-cphelps
service:
    pipelines:
        metrics:
            receivers:
                - hostmetrics
            processors:
                - batch
            exporters:
                - googlecloud

```
