### ISSUE TITLE
Formatting error messages in logs to report error events to GCP Error Reporting service

### ISSUE THREAD

**Issue by pelegb** [GoogleCloudPlatform/opentelemetry-operations-go#665]
The current Google Cloud Exporter for logs exports the `textPayload` field. In order for log lines to appear in GCP's Error Reporting service they need to have the following format according to the documentation [here:](https://cloud.google.com/error-reporting/docs/formatting-error-messages#log-text)
`"jsonPayload": {
      "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
      "message": "Text message"
    },`

Supporting this use case would greatly assist in integration GMP with GCP's other services, specifically Error Reporting.

Thanks

**Comment by damemi** [comment]
The logs exporter does use the `jsonPayload` field if the OTel entry's [body type](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/8d8eba3399098331775e8bfae5e8beb37a05b788/exporter/collector/logs.go#L521) is an object/map. So, I think you could manually set the `@type` key on the log body with the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) for errors. 

To do this automatically, we could use the severity level in the log and automatically use a map payload if it's an error (with the added `@type` field). I'd also wrap this in a config option.

In the meantime, @pelegb please give the manual workaround with the transform processor a try to see if that helps and let us know. Thanks!

**Comment by shkrid** [comment]
@damemi seems it works.
Thank you!
```
      transform/error_reporting:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - set(cache["message"], body)
              - set(cache["@type"], "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent")
              - set(cache["stack_trace"], attributes["exception.stacktrace"])
              - set(resource.attributes["service"], resource.attributes["service.name"])
              - set(resource.attributes["version"], resource.attributes["service.version"])
              - set(cache["serviceContext"], resource.attributes)
              - keep_keys(cache["serviceContext"], ["service", "version"])
              - set(body, cache) where severity_number == 17
```
