### ISSUE TITLE
exporter/collector/logs: segfault when setting `gcp.source_location`

### ISSUE THREAD

**Issue by quentinmit** [GoogleCloudPlatform/opentelemetry-operations-go#792]
It looks like this is coming from

https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/02b243a6fbedbdc6118f2e2dc34aced98fc70dba/exporter/collector/logs.go#L397

which calls `sourceLocation.Bytes().AsRaw()` without confirming that the attribute has a bytes value.

## Stacktrace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xce2fbc]

goroutine 127 [running]:
go.opentelemetry.io/collector/pdata/pcommon.ByteSlice.AsRaw(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0016/pcommon/generated_byteslice.go:37
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.logMapper.logToSplitEntries({{0xc0019b22a0}, {{0xc00155a030, 0xa}, {0xc001d1a810, 0x26}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.44.0/logs.go:397 +0x47c
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.logMapper.createEntries({{0xc0019b22a0}, {{0xc00155a030, 0xa}, {0xc001d1a810, 0x26}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.44.0/logs.go:282 +0x8d4
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*LogsExporter).PushLogs(0xc001eb4800, {0x5b60de0, 0xc001f9c930}, {0xc001b8e468?, 0xc001f9a2b0?})
        /root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.44.0/logs.go:199 +0xca
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export(0x19?, {0x5b60de0?, 0xc001f9c930?})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/logs.go:60 +0x32
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc001ece240, {0x5b76fa0, 0xc001f9c900})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/timeout_sender.go:41 +0x9c
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseRequestSender).send(0xc001ed8680?, {0x5b76fa0?, 0xc001f9c900?})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/common.go:36 +0x25
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc001ece228, {0x5b76fa0, 0xc001f9c900})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/logs.go:176 +0x82
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).send(0xc001ae9b00, {0x5b76fa0, 0xc001f9c900})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/queue_sender.go:168 +0x40f
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).send(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/common.go:196
go.opentelemetry.io/collector/exporter/exporterhelper.NewLogsExporter.func1({0x5b60e18?, 0xc0019dfa90}, {0xc001b8e468?, 0xc001f9a2b0?})
        /root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.87.0/exporterhelper/logs.go:100 +0xe4
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.87.0/logs.go:25
go.opentelemetry.io/collector/processor/processorhelper.NewLogsProcessor.func1({0x5b60e18, 0xc0019dfa90}, {0xc001b8e468?, 0xc001f9a2b0?})
        /root/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.87.0/processorhelper/logs.go:60 +0x1f6
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.87.0/logs.go:25
go.opentelemetry.io/collector/processor/processorhelper.NewLogsProcessor.func1({0x5b60e18, 0xc0019dfa90}, {0xc001b8e468?, 0xc001f9a2b0?})
        /root/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.87.0/processorhelper/logs.go:60 +0x1f6
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.87.0/logs.go:25
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs(...)
        /root/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.87.0/logs.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry.(*logsConsumer).ConsumeLogs(0xc002145740, {0x5b60e18?, 0xc0019dfa90?}, {0xc001b8e468?, 0xc001f9a2b0?})
        /root/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.87.0/consumerretry/logs.go:37 +0x19e
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop(0xc001ae9dd0, {0x5b60e18, 0xc0019dfa90})
        /root/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.87.0/adapter/receiver.go:124 +0x1be
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).Start in goroutine 1
        /root/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.87.0/adapter/receiver.go:68 +0x285
```
## Reproducer
Here's a sample input log and config you can use to reproduce the segfault. (I'm sure you could also just do it with a `otlpjsonfilereceiver` and skip the transformation, but I'm not sure how to easily set up such a test case.)

`input.log`
```json
{"message": "test message", "logging.googleapis.com/sourceLocation": {"file": "file", "line": "1", "function": "function"}}
```
`config.yaml`:
```yaml
exporters:
  googlecloud/otel:
    log:
      default_log_name: my-log-name
      endpoint: 127.0.0.1:46851
      use_insecure: true
    project: my-project
    sending_queue:
      enabled: false
processors:
  transform/input_0:
    log_statements:
      context: log
      statements:
      - set(body, ParseJSON(body))
      - set(attributes["gcp.source_location"], body["logging.googleapis.com/sourceLocation"])
      - delete_key(body, "logging.googleapis.com/sourceLocation")
receivers:
  filelog/input:
    exclude: []
    include:
    - input.log
    include_file_name: false
    start_at: beginning
service:
  pipelines:  
    logs/input:
      exporters:
      - googlecloud/otel
      processors:
      - transform/input_0
      receivers:
      - filelog/input
```
