### ISSUE TITLE
GMP exporter should convert Int values to Double

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#798]
~~GMP only accepts Double values.  Sending it an int will cause the metric to be rejected.~~
This is not correct.  GMP accepts int and double values.

This can be done with the transform processor today, although I think this needs to be filtered so it only applies to int valued datapoints:

```
      transform/inttodouble:
        metric_statements:
          - context: datapoint
            statements:
              # GMP metrics are expected to be double
              - set(value_double, Double(value_int))
```

Ideally, the exporter should handle this, rather than requiring users to add processors.  I encountered this when using the spanmetrics exporter, which produces int-valued metrics.
