### ISSUE TITLE
Offline Queuing of Logs and Metrics

### ISSUE THREAD

**Issue by skrawn** [GoogleCloudPlatform/opentelemetry-operations-go#812]
I was trying to deploy the OpenTelemetry Collector on some embedded Linux devices and since these devices are on cellular connections, they are not always able to reach the internet. But I'd still like to be able to queue metrics and logs for upload once the device re-establishes connection. Am I correct that this will work with the `sending_queue`, `retry_on_failure` and `file_storage` components, like this:

```
extensions:
  file_storage:
    directory: /etc/otelcol/offline
    compaction:
      on_start: true
      directory: /etc/otelcol/offline
      max_transaction_size: 65_536
    fsync: true

exporters:
  googlemanagedprometheus:
    metric:
      compression: gzip
    retry_on_failure:
      enabled: true
      max_elapsed_time: 86400s
    sending_queue:
      enabled: true
      storage: file_storage
      num_consumers: 1
      queue_size: 1000
```

The reason I ask is that `retry_on_failure` was not implemented on the Google Managed Prometheus exporter and so requests that timeout due to network failures result in metrics getting discarded. If the `retry_on_failure` component works as expected, I'll probably try to implement it for the GMP exporter. I also see that there are some problems with `retry_on_failure` depending on the exporter, like [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19203) one for the Google Cloud exporter, so maybe there is some limitation within the collector that I am not aware of?
