### ISSUE TITLE
GMP exporter should deduplicate resources when writing target_info

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#834]
When using the hostmetrics receiver, each scraper seems to emit metrics under its own resource, which causes DuplicateTimeseries errors when using the GMP exporter, as each resource is turned into its own target_info metric.  Since metrics all come from the same host, they all collide.

The exporter should handle cases like these by deduplicating resource or target_info metrics.

**Comment by dashpole** [comment]
To work around the Duplicate Timeseries error, use this config:

```yaml
      googlemanagedprometheus:
        metric:
          extra_metrics_config:
            enable_target_info: false
```
